// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Jam struct {
	ID             int32
	CreatedBy      pgtype.Text
	Name           pgtype.Text
	StartTimestamp pgtype.Timestamp
	EndTimestamp   pgtype.Timestamp
	Location       pgtype.Text
}

type JamParticipant struct {
	ID    int32
	Email pgtype.Text
	JamID pgtype.Int4
}

type Post struct {
	ID        int32
	CreatedBy string
	Title     string
	Content   pgtype.Text
}
